name: flutter_sinusoidals
description: A flutter package which helps visualizing waves.
version: 0.0.1
homepage: https://github.com/dungnv2602/flutter_sinusoidals

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter